import React from "react";

export type ThemeMode = "system" | "light" | "dark";
export type ResolvedTheme = "light" | "dark";
export type AccentColor = "green" | "purple" | "blue" | "pink";
export type AppIcon = "classic" | "bright";
export type LocaleCode =
  | ""
  | "zh_CN"
  | "zh_TW"
  | "en_US"
  | "ar_SA"
  | "de_DE"
  | "es_ES"
  | "fr_FR"
  | "id_ID"
  | "it_IT"
  | "ja_JP"
  | "ko_KR"
  | "pt_BR"
  | "ru_RU"
  | "th_TH"
  | "tr_TR"
  | "vi_VN";

type PreferencesState = {
  themeMode: ThemeMode;
  accentColor: AccentColor;
  appIcon: AppIcon;
  localeCode: LocaleCode;
};

export type TranslationKey = string;
export type TranslationValues = Record<string, string | number>;

const defaultPreferences: PreferencesState = {
  themeMode: "system",
  accentColor: "green",
  appIcon: "classic",
  localeCode: "",
};

const storageKey = "arkme-demo.preferences";

export const supportedLocales: Array<{
  code: LocaleCode;
  displayName: string;
  locale?: string;
  dir?: "ltr" | "rtl";
}> = [
  { code: "", displayName: "自动使用系统语言" },
  { code: "zh_CN", displayName: "简体中文", locale: "zh-CN" },
  { code: "zh_TW", displayName: "繁體中文", locale: "zh-TW" },
  { code: "en_US", displayName: "English", locale: "en-US" },
  { code: "ar_SA", displayName: "العربية", locale: "ar-SA", dir: "rtl" },
  { code: "de_DE", displayName: "Deutsch", locale: "de-DE" },
  { code: "es_ES", displayName: "Español", locale: "es-ES" },
  { code: "fr_FR", displayName: "Français", locale: "fr-FR" },
  { code: "id_ID", displayName: "Bahasa Indonesia", locale: "id-ID" },
  { code: "it_IT", displayName: "Italiano", locale: "it-IT" },
  { code: "ja_JP", displayName: "日本語", locale: "ja-JP" },
  { code: "ko_KR", displayName: "한국어", locale: "ko-KR" },
  { code: "pt_BR", displayName: "Português", locale: "pt-BR" },
  { code: "ru_RU", displayName: "Русский", locale: "ru-RU" },
  { code: "th_TH", displayName: "ไทย", locale: "th-TH" },
  { code: "tr_TR", displayName: "Türkçe", locale: "tr-TR" },
  { code: "vi_VN", displayName: "Tiếng Việt", locale: "vi-VN" },
];

export const accentColorOptions: Array<{
  key: AccentColor;
  color: string;
  border: string;
}> = [
  { key: "green", color: "#09B83E", border: "rgba(136, 214, 108, 0.5)" },
  { key: "purple", color: "#8363FF", border: "rgba(131, 99, 255, 0.5)" },
  { key: "blue", color: "#0E9DEC", border: "rgba(90, 178, 255, 0.5)" },
  { key: "pink", color: "#E04DAE", border: "rgba(253, 124, 159, 0.5)" },
];

const translations: Record<string, Record<TranslationKey, string>> = {
  "zh-CN": {
    "tabs.records": "快记",
    "tabs.arrangements": "安排",
    "tabs.insight": "洞见",
    "tabs.mine": "我的",
    "search.close": "关闭搜索",
    "search.placeholder": "搜索快记...",
    "search.label": "搜索",
    "search.cancel": "取消",
    "search.clear": "清空搜索",
    "search.recent": "最近在搜",
    "search.quickSearch": "快速查找",
    "search.tags": "标签",
    "search.defaultTags": "#Demo,#快记,#即我,#AI",
    "search.quick.image": "图片/视频",
    "search.quick.audio": "语音",
    "search.quick.link": "外部链接",
    "search.quick.file": "文件",
    "search.quick.longArticle": "长文",
    "search.quick.contact": "联系人",
    "search.tabRecords": "快记",
    "search.tabTopics": "主题",
    "search.filter": "筛选",
    "search.noResult": "没有找到“{keyword}”相关内容\n换个关键词再试试吧",
    "search.topicCount": "{count} 条快记",
    "search.topicQuickIcon": "记",
    "drawer.closeMask": "关闭侧边栏遮罩",
    "drawer.label": "侧边栏",
    "drawer.title": "对话列表",
    "drawer.footerTitle": "候选人 Demo",
    "drawer.footerDesc": "此为即我app不带后端功能的部分前端复刻版，供候选人笔试题使用",
    "guide.title": "答题说明",
    "guide.pinned": "置顶",
    "guide.subtitle": "开始前请先阅读答题规范",
    "ai.title": "和AI编程工具对话",
    "ai.emptyTitle": "当前还没有 AI 编程对话记录",
    "ai.emptyDesc": "每次迭代后，Codex 会把输入输出同步写入这里。",
    "ai.rounds": "轮迭代记录",
    "ai.userInput": "用户输入",
    "ai.output": "AI最终输出",
    "ai.changedFiles": "本轮改动文件",
    "ai.verification": "验证结果",
    "sendToSelf.title": "发给自己",
    "sendToSelf.icon": "自",
    "sendToSelf.privateTag": "私密",
    "sendToSelf.open": "进入发给自己",
    "sendToSelf.recordCount": "条记录",
    "sendToSelf.emptyPreview": "暂无快记",
    "sendToSelf.demo1": "把今天想到的侧边栏入口先记下来：发给自己要能承接首页快记。",
    "sendToSelf.demo2": "晚点继续补一版真实使用场景，让首页和对话里的记录保持同步。",
    "homeMessagePreview.label": "新消息",
    "common.back": "返回",
    "common.done": "完成",
    "common.selected": "已选择",
    "common.vip": "会员",
    "common.openMenu": "打开侧边栏",
    "common.unreadCount": "条未读",
    "insight.title": "洞见",
    "insight.emptyTitle": "洞见自我，自在生活",
    "insight.emptyDesc": "此版块为团队内测板块，内容暂不对外开放。",
    "mine.world": "我的世界",
    "mine.user": "即我用户",
    "mine.memberTitle": "开通即我会员",
    "mine.memberDesc": "享受多种权益",
    "mine.memberAction": "立即开通",
    "mine.statsTitle": "时至今日，你用即我",
    "mine.statsButton": "统计",
    "mine.dataTitle": "数据管理",
    "mine.dataDesc": "你的数据真正属于你",
    "mine.settings": "设置",
    "mine.settingsDesc": "隐私权限管理",
    "mine.about": "关于",
    "mine.aboutDesc": "反馈建议、参加活动",
    "mine.avatarAlt": "默认头像",
    "mine.storage": "0.9G/5G",
    "mine.stat1": "持续记录 37 天",
    "mine.stat2": "在 12 个位置，产生 {count} 条快记",
    "mine.stat3": "记录总时长 426 分钟",
    "mine.stat4": "共计 {words} 字",
    "mine.tagImportExport": "导入导出",
    "mine.tagDataSecurity": "数据安全",
    "mine.tagPrivacy": "隐私保护",
    "about.userAgreement": "用户协议",
    "about.privacyTerms": "隐私条款",
    "about.privacyStatement": "隐私保护声明",
    "about.contactAuthor": "联系作者",
    "about.contactAuthorDesc": "bug反馈/功能建议/问题咨询/或...找我闲聊",
    "about.appName": "即我",
    "about.appReview": "应用评价",
    "about.appReviewTip": "好用的话烦请给个好评",
    "about.socialChannels": "公众号/小红书/抖音/即刻/微博",
    "about.wechatOfficial": "公众号",
    "about.xiaohongshu": "小红书",
    "about.douyin": "抖音",
    "about.jike": "即刻",
    "about.weibo": "微博",
    "settings.title": "设置",
    "settings.appearance": "外观样式设置",
    "settings.appearanceDesc": "主题、强调色与应用图标",
    "settings.language": "语言设置",
    "settings.languageDesc": "选择应用显示语言",
    "settings.languageSheetDesc": "选择应用显示语言",
    "settings.followSystem": "自动使用系统语言",
    "settings.current": "当前",
    "appearance.title": "外观样式设置",
    "appearance.theme": "主题模式",
    "appearance.themeSystem": "跟随系统",
    "appearance.themeLight": "浅色",
    "appearance.themeDark": "深色",
    "appearance.accent": "界面强调色",
    "appearance.icon": "应用图标",
    "appearance.freeLimit": "Demo 中保留会员条件判断：亮色应用图标为会员能力。",
    "appearance.iconClassic": "经典",
    "appearance.iconBright": "亮色",
    "accent.green": "绿色",
    "accent.purple": "紫色",
    "accent.blue": "蓝色",
    "accent.pink": "粉色",
    "composer.placeholder": "单击文字，长按语音",
    "composer.recording": "正在录音，松开发送",
    "composer.textPlaceholder": "记录此刻想法...",
    "composer.send": "发送",
    "records.demo1": "今天先把候选人笔试 Demo 搭起来，只保留移动端首页、底部导航和快记输入体验。",
    "records.demo2": "候选人可以在这个移动端基底上新增自己的模块入口、列表和详情交互。",
    "records.demo3": "视觉上沿用即我的灰白底、绿色主色、轻量圆角和底部输入框。",
    "records.voiceRecord": "语音记录 00:03",
    "records.title": "我的快记",
    "records.subtitle": "从这里开始记录想法",
    "records.noMatches": "没有匹配的快记",
    "records.emptyTitle": "记录你的每一刻",
    "records.noMatchDesc": "换一个关键词试试",
    "records.emptyDesc": "快记是你的私人记事本，随时记录想法、灵感和生活片段",
    "records.openSource": "进入对应对话",
    "recordReference.extendedFrom": "引用",
    "recordDetail.title": "快记详情",
    "recordDetail.close": "关闭详情",
    "recordDetail.untitled": "无标题",
    "recordDetail.wordUnit": "字",
    "recordDetail.wordCount": "字数",
    "recordDetail.duration": "记录时长",
    "recordDetail.review": "查阅/回顾",
    "recordDetail.share": "分享",
    "recordDetail.source": "来源",
    "recordDetail.original": "原文内容",
    "recordDetail.sourceLocation": "来源位置",
    "recordDetail.createdAt": "开始时间",
    "recordDetail.completedAt": "完成时间",
    "recordDetail.syncStatus": "同步时间",
    "recordDetail.localSynced": "本地 Demo",
    "recordDetail.quickNoteSource": "我的快记",
    "recordDetail.secondsSuffix": "s",
    "recordDetail.timesSuffix": "次",
    "recordDetail.thoughtTitle": "阿森有想法",
    "recordDetail.thoughtDesc": "这条快记可以继续延展成行动、问题或补充记忆。",
    "recordDetail.similarTitle": "相似快记",
    "recordDetail.similarDemo1": "把当前想法拆成下一步行动，方便之后继续跟进。",
    "recordDetail.similarDemo2": "围绕同一主题补充背景、决定和待确认事项。",
    "recordDetail.extendsPrefix": "共 ",
    "recordDetail.extendsSuffix": " 条延展",
    "recordDetail.noExtends": "还没有延展，继续补充评论后会显示在这里。",
    "recordDetail.extendPlaceholder": "继续延展评论...",
    "recordDetail.sendExtend": "发送",
    "recordDetail.inputMenu": "打开输入菜单",
    "recordDetail.noLocation": "暂无位置信息",
    "recordDetail.me": "我",
    "recordSnapshot.title": "记忆快照",
    "recordSnapshot.close": "关闭记忆快照",
    "recordSnapshot.untitled": "无标题",
    "recordSnapshot.quickNoteSource": "我的快记",
    "recordAction.close": "关闭操作菜单",
    "recordAction.copy": "复制",
    "recordAction.detail": "详情",
    "recordAction.fullscreen": "全屏",
    "recordAction.extend": "延展",
    "recordAction.memorySnapshot": "记忆快照",
    "recordAction.moreDetail": "查看详情",
    "recordAction.more": "更多",
    "chat.loadingMore": "加载更多...",
    "chat.loadMore": "加载更多",
    "time.today": "今天",
    "time.yesterday": "昨天",
    "time.dayBeforeYesterday": "前天",
    "time.justNow": "刚刚",
    "time.minutesAgo": "分钟前",
    "time.hoursAgo": "小时前",
    "guide.avatar": "说",
    "guide.scope": "移动端笔试规范",
    "guide.message1": "开始答题前，请先让 Codex 阅读 AGENTS.md 和 docs/candidate-rules.md，并按其中的答题规范完成后续需求。",
    "guide.message2": "每轮需求需要先理解目标和影响范围，再阅读相关代码。修改范围要聚焦，不做无关重构。",
    "guide.message3": "每完成一轮迭代，都要把时间、用户输入、AI 最终输出、改动文件和验证结果追加到自己的 docs/codex-logs/ 个人日志。",
    "guide.message4": "最终提交 GitHub 前，请运行 pnpm verify:answer，确保 lint、build、迭代日志和答题规范检查都通过。",
    "guide.message5": "面试官会结合最终代码、Git 提交历史和 Codex 迭代日志，观察你使用 AI 迭代项目的过程。",
  },
  "zh-TW": {
    "tabs.records": "快記",
    "tabs.arrangements": "安排",
    "tabs.insight": "洞見",
    "tabs.mine": "我的",
    "search.close": "關閉搜尋",
    "search.placeholder": "搜尋快記...",
    "search.label": "搜尋",
    "search.cancel": "取消",
    "search.clear": "清空搜尋",
    "search.recent": "最近在搜",
    "search.quickSearch": "快速查找",
    "search.tags": "標籤",
    "search.defaultTags": "#Demo,#快記,#即我,#AI",
    "search.quick.image": "圖片/影片",
    "search.quick.audio": "語音",
    "search.quick.link": "外部連結",
    "search.quick.file": "檔案",
    "search.quick.longArticle": "長文",
    "search.quick.contact": "聯絡人",
    "search.tabRecords": "快記",
    "search.tabTopics": "主題",
    "search.filter": "篩選",
    "search.noResult": "沒有找到「{keyword}」相關內容\n換個關鍵詞再試試吧",
    "search.topicCount": "{count} 條快記",
    "search.topicQuickIcon": "記",
    "drawer.closeMask": "關閉側邊欄遮罩",
    "drawer.label": "側邊欄",
    "drawer.title": "對話列表",
    "drawer.footerTitle": "候選人 Demo",
    "drawer.footerDesc": "此為即我 app 不帶後端功能的部分前端復刻版，供候選人筆試題使用",
    "guide.title": "答題說明",
    "guide.pinned": "置頂",
    "guide.subtitle": "開始前請先閱讀答題規範",
    "ai.title": "和 AI 編程工具對話",
    "ai.emptyTitle": "目前還沒有 AI 編程對話記錄",
    "ai.emptyDesc": "每次迭代後，Codex 會把輸入輸出同步寫入這裡。",
    "ai.rounds": "輪迭代記錄",
    "ai.userInput": "使用者輸入",
    "ai.output": "AI 最終輸出",
    "ai.changedFiles": "本輪改動檔案",
    "ai.verification": "驗證結果",
    "sendToSelf.title": "發給自己",
    "sendToSelf.icon": "自",
    "sendToSelf.privateTag": "私密",
    "sendToSelf.open": "進入發給自己",
    "sendToSelf.recordCount": "條記錄",
    "sendToSelf.emptyPreview": "暫無快記",
    "sendToSelf.demo1": "把今天想到的側邊欄入口先記下來：發給自己要能承接首頁快記。",
    "sendToSelf.demo2": "晚點繼續補一版真實使用場景，讓首頁和對話裡的記錄保持同步。",
    "homeMessagePreview.label": "新訊息",
    "settings.title": "設定",
    "settings.appearance": "外觀樣式設定",
    "settings.appearanceDesc": "主題、強調色與應用圖示",
    "settings.language": "語言設定",
    "settings.languageDesc": "選擇應用顯示語言",
    "settings.languageSheetDesc": "選擇應用顯示語言",
    "settings.followSystem": "自動使用系統語言",
    "settings.current": "目前",
    "appearance.title": "外觀樣式設定",
    "appearance.theme": "主題模式",
    "appearance.themeSystem": "跟隨系統",
    "appearance.themeLight": "淺色",
    "appearance.themeDark": "深色",
    "appearance.accent": "介面強調色",
    "appearance.icon": "應用圖示",
    "appearance.freeLimit": "Demo 中保留會員條件判斷：亮色應用圖示為會員能力。",
    "common.back": "返回",
    "common.done": "完成",
    "common.selected": "已選擇",
    "common.vip": "會員",
    "common.openMenu": "開啟側邊欄",
    "common.unreadCount": "則未讀",
    "insight.title": "洞見",
    "insight.emptyTitle": "洞見自我，自在生活",
    "insight.emptyDesc": "此版塊為團隊內測版塊，內容暫不對外開放。",
    "mine.world": "我的世界",
    "mine.user": "即我使用者",
    "mine.memberTitle": "開通即我會員",
    "mine.memberDesc": "享受多種權益",
    "mine.memberAction": "立即開通",
    "mine.statsTitle": "時至今日，你用即我",
    "mine.statsButton": "統計",
    "mine.dataTitle": "資料管理",
    "mine.dataDesc": "你的資料真正屬於你",
    "mine.settings": "設定",
    "mine.settingsDesc": "隱私權限管理",
    "mine.about": "關於",
    "mine.aboutDesc": "回饋建議、參加活動",
    "mine.avatarAlt": "預設頭像",
    "mine.storage": "0.9G/5G",
    "mine.stat1": "持續記錄 37 天",
    "mine.stat2": "在 12 個位置，產生 {count} 條快記",
    "mine.stat3": "記錄總時長 426 分鐘",
    "mine.stat4": "共計 {words} 字",
    "mine.tagImportExport": "匯入匯出",
    "mine.tagDataSecurity": "資料安全",
    "mine.tagPrivacy": "隱私保護",
    "about.userAgreement": "使用者協議",
    "about.privacyTerms": "隱私條款",
    "about.privacyStatement": "隱私保護聲明",
    "about.contactAuthor": "聯絡作者",
    "about.contactAuthorDesc": "bug 回饋/功能建議/問題諮詢/或...找我閒聊",
    "about.appName": "即我",
    "about.appReview": "應用評價",
    "about.appReviewTip": "好用的話煩請給個好評",
    "about.socialChannels": "公眾號/小紅書/抖音/即刻/微博",
    "about.wechatOfficial": "公眾號",
    "about.xiaohongshu": "小紅書",
    "about.douyin": "抖音",
    "about.jike": "即刻",
    "about.weibo": "微博",
    "accent.green": "綠色",
    "accent.purple": "紫色",
    "accent.blue": "藍色",
    "accent.pink": "粉色",
    "appearance.iconClassic": "經典",
    "appearance.iconBright": "亮色",
    "composer.placeholder": "單擊文字，長按語音",
    "composer.recording": "正在錄音，鬆開發送",
    "composer.textPlaceholder": "記錄此刻想法...",
    "composer.send": "發送",
    "records.demo1": "今天先把候選人筆試 Demo 搭起來，只保留行動端首頁、底部導覽和快記輸入體驗。",
    "records.demo2": "候選人可以在這個行動端基底上新增自己的模組入口、列表和詳情互動。",
    "records.demo3": "視覺上沿用即我的灰白底、綠色主色、輕量圓角和底部輸入框。",
    "records.voiceRecord": "語音記錄 00:03",
    "records.title": "我的快記",
    "records.subtitle": "從這裡開始記錄想法",
    "records.noMatches": "沒有匹配的快記",
    "records.emptyTitle": "記錄你的每一刻",
    "records.noMatchDesc": "換一個關鍵詞試試",
    "records.emptyDesc": "快記是你的私人記事本，隨時記錄想法、靈感和生活片段",
    "records.openSource": "進入對應對話",
    "recordReference.extendedFrom": "引用",
    "recordDetail.title": "快記詳情",
    "recordDetail.close": "關閉詳情",
    "recordDetail.untitled": "無標題",
    "recordDetail.wordUnit": "字",
    "recordDetail.wordCount": "字數",
    "recordDetail.duration": "記錄時長",
    "recordDetail.review": "查閱/回顧",
    "recordDetail.share": "分享",
    "recordDetail.source": "來源",
    "recordDetail.original": "原文內容",
    "recordDetail.sourceLocation": "來源位置",
    "recordDetail.createdAt": "開始時間",
    "recordDetail.completedAt": "完成時間",
    "recordDetail.syncStatus": "同步時間",
    "recordDetail.localSynced": "本地 Demo",
    "recordDetail.quickNoteSource": "我的快記",
    "recordDetail.secondsSuffix": "s",
    "recordDetail.timesSuffix": "次",
    "recordDetail.thoughtTitle": "阿森有想法",
    "recordDetail.thoughtDesc": "這條快記可以繼續延展成行動、問題或補充記憶。",
    "recordDetail.similarTitle": "相似快記",
    "recordDetail.similarDemo1": "把目前想法拆成下一步行動，方便之後繼續跟進。",
    "recordDetail.similarDemo2": "圍繞同一主題補充背景、決定和待確認事項。",
    "recordDetail.extendsPrefix": "共 ",
    "recordDetail.extendsSuffix": " 條延展",
    "recordDetail.noExtends": "還沒有延展，繼續補充評論後會顯示在這裡。",
    "recordDetail.extendPlaceholder": "繼續延展評論...",
    "recordDetail.sendExtend": "傳送",
    "recordDetail.inputMenu": "開啟輸入選單",
    "recordDetail.noLocation": "暫無位置資訊",
    "recordDetail.me": "我",
    "recordSnapshot.title": "記憶快照",
    "recordSnapshot.close": "關閉記憶快照",
    "recordSnapshot.untitled": "無標題",
    "recordSnapshot.quickNoteSource": "我的快記",
    "recordAction.close": "關閉操作選單",
    "recordAction.copy": "複製",
    "recordAction.detail": "詳情",
    "recordAction.fullscreen": "全螢幕",
    "recordAction.extend": "延展",
    "recordAction.memorySnapshot": "記憶快照",
    "recordAction.moreDetail": "查看詳情",
    "recordAction.more": "更多",
    "chat.loadingMore": "載入更多...",
    "chat.loadMore": "載入更多",
    "time.today": "今天",
    "time.yesterday": "昨天",
    "time.dayBeforeYesterday": "前天",
    "time.justNow": "剛剛",
    "time.minutesAgo": "分鐘前",
    "time.hoursAgo": "小時前",
    "guide.avatar": "說",
    "guide.scope": "行動端筆試規範",
    "guide.message1": "開始答題前，請先讓 Codex 閱讀 AGENTS.md 和 docs/candidate-rules.md，並按其中的答題規範完成後續需求。",
    "guide.message2": "每輪需求需要先理解目標和影響範圍，再閱讀相關程式碼。修改範圍要聚焦，不做無關重構。",
    "guide.message3": "每完成一輪迭代，都要把時間、使用者輸入、AI 最終輸出、改動檔案和驗證結果追加到自己的 docs/codex-logs/ 個人日誌。",
    "guide.message4": "最終提交 GitHub 前，請執行 pnpm verify:answer，確保 lint、build、迭代日誌和答題規範檢查都通過。",
    "guide.message5": "面試官會結合最終程式碼、Git 提交歷史和 Codex 迭代日誌，觀察你使用 AI 迭代專案的過程。",
  },
  "en-US": {
    "tabs.records": "Notes",
    "tabs.arrangements": "Plans",
    "tabs.insight": "Insight",
    "tabs.mine": "Me",
    "search.close": "Close search",
    "search.placeholder": "Search notes...",
    "search.label": "Search",
    "search.cancel": "Cancel",
    "search.clear": "Clear search",
    "search.recent": "Recent searches",
    "search.quickSearch": "Quick search",
    "search.tags": "Tags",
    "search.defaultTags": "#Demo,#Notes,#Jiwo,#AI",
    "search.quick.image": "Images/Videos",
    "search.quick.audio": "Voice",
    "search.quick.link": "External links",
    "search.quick.file": "Files",
    "search.quick.longArticle": "Long reads",
    "search.quick.contact": "Contacts",
    "search.tabRecords": "Notes",
    "search.tabTopics": "Topics",
    "search.filter": "Filter",
    "search.noResult": "No results for \"{keyword}\"\nTry another keyword",
    "search.topicCount": "{count} quick notes",
    "search.topicQuickIcon": "N",
    "drawer.closeMask": "Close drawer overlay",
    "drawer.label": "Sidebar",
    "drawer.title": "Conversation list",
    "drawer.footerTitle": "Candidate Demo",
    "drawer.footerDesc": "A partial frontend replica of the Jiwo app without backend features, for candidate written tests.",
    "guide.title": "Instructions",
    "guide.pinned": "Pinned",
    "guide.subtitle": "Read the answer rules first",
    "ai.title": "AI coding tool chat",
    "ai.emptyTitle": "No AI coding conversation yet",
    "ai.emptyDesc": "After each iteration, Codex writes the input and output here.",
    "ai.rounds": "iteration records",
    "ai.userInput": "User input",
    "ai.output": "AI final output",
    "ai.changedFiles": "Changed files",
    "ai.verification": "Verification",
    "sendToSelf.title": "Send to self",
    "sendToSelf.icon": "Me",
    "sendToSelf.privateTag": "Private",
    "sendToSelf.open": "Open Send to self",
    "sendToSelf.recordCount": " notes",
    "sendToSelf.emptyPreview": "No quick notes yet",
    "sendToSelf.demo1": "Save the sidebar idea here first: Send to self should collect quick notes from the home screen.",
    "sendToSelf.demo2": "Add a more realistic usage note later so home and the dedicated conversation stay in sync.",
    "homeMessagePreview.label": "New message",
    "common.back": "Back",
    "common.done": "Done",
    "common.selected": "Selected",
    "common.vip": "VIP",
    "common.openMenu": "Open sidebar",
    "common.unreadCount": " unread",
    "insight.title": "Insight",
    "insight.emptyTitle": "See yourself, live freely",
    "insight.emptyDesc": "This section is in internal team testing and is not open to the public yet.",
    "mine.world": "My World",
    "mine.user": "Jiwo User",
    "mine.memberTitle": "Activate Jiwo VIP",
    "mine.memberDesc": "Unlock more benefits",
    "mine.memberAction": "Activate",
    "mine.statsTitle": "Your Jiwo journey",
    "mine.statsButton": "Stats",
    "mine.dataTitle": "Data management",
    "mine.dataDesc": "Your data belongs to you",
    "mine.settings": "Settings",
    "mine.settingsDesc": "Privacy and permissions",
    "mine.about": "About",
    "mine.aboutDesc": "Feedback and events",
    "mine.avatarAlt": "Default avatar",
    "mine.storage": "0.9G/5G",
    "mine.stat1": "Recorded for 37 days",
    "mine.stat2": "{count} quick notes across 12 places",
    "mine.stat3": "426 minutes recorded",
    "mine.stat4": "{words} words in total",
    "mine.tagImportExport": "Import/Export",
    "mine.tagDataSecurity": "Data security",
    "mine.tagPrivacy": "Privacy",
    "about.userAgreement": "User agreement",
    "about.privacyTerms": "Privacy terms",
    "about.privacyStatement": "Privacy protection statement",
    "about.contactAuthor": "Contact author",
    "about.contactAuthorDesc": "Bug reports, feature ideas, questions, or a casual chat",
    "about.appName": "Jiwo",
    "about.appReview": "App review",
    "about.appReviewTip": "Please leave a review if it helps",
    "about.socialChannels": "WeChat/Xiaohongshu/Douyin/Jike/Weibo",
    "about.wechatOfficial": "WeChat official account",
    "about.xiaohongshu": "Xiaohongshu",
    "about.douyin": "Douyin",
    "about.jike": "Jike",
    "about.weibo": "Weibo",
    "settings.title": "Settings",
    "settings.appearance": "Appearance",
    "settings.appearanceDesc": "Theme, accent color and app icon",
    "settings.language": "Language",
    "settings.languageDesc": "Choose app display language",
    "settings.languageSheetDesc": "Choose app display language",
    "settings.followSystem": "Use system language automatically",
    "settings.current": "Current",
    "appearance.title": "Appearance",
    "appearance.theme": "Theme mode",
    "appearance.themeSystem": "Follow system",
    "appearance.themeLight": "Light",
    "appearance.themeDark": "Dark",
    "appearance.accent": "Accent color",
    "appearance.icon": "App icon",
    "appearance.freeLimit": "The demo keeps VIP conditions: the bright app icon is a VIP capability.",
    "appearance.iconClassic": "Classic",
    "appearance.iconBright": "Bright",
    "accent.green": "Green",
    "accent.purple": "Purple",
    "accent.blue": "Blue",
    "accent.pink": "Pink",
    "composer.placeholder": "Tap for text, hold for voice",
    "composer.recording": "Recording, release to send",
    "composer.textPlaceholder": "Record this moment...",
    "composer.send": "Send",
    "records.demo1": "Today we are setting up the candidate exam demo with only the mobile home page, bottom tabs, and quick note input experience.",
    "records.demo2": "Candidates can add their own module entry, list, and detail interactions on top of this mobile base.",
    "records.demo3": "The visual style follows Jiwo: gray-white surfaces, green primary color, light radii, and a bottom input box.",
    "records.voiceRecord": "Voice note 00:03",
    "records.title": "My Quick Notes",
    "records.subtitle": "Start recording ideas here",
    "records.noMatches": "No matching notes",
    "records.emptyTitle": "Record every moment",
    "records.noMatchDesc": "Try another keyword",
    "records.emptyDesc": "Quick Notes is your private notebook for thoughts, ideas, and life fragments.",
    "records.openSource": "Open source conversation",
    "recordReference.extendedFrom": "Referenced note",
    "recordDetail.title": "Note details",
    "recordDetail.close": "Close details",
    "recordDetail.untitled": "Untitled",
    "recordDetail.wordUnit": " chars",
    "recordDetail.wordCount": "Words",
    "recordDetail.duration": "Duration",
    "recordDetail.review": "Views",
    "recordDetail.share": "Shares",
    "recordDetail.source": "Source",
    "recordDetail.original": "Original text",
    "recordDetail.sourceLocation": "Source",
    "recordDetail.createdAt": "Started",
    "recordDetail.completedAt": "Completed",
    "recordDetail.syncStatus": "Sync time",
    "recordDetail.localSynced": "Local demo",
    "recordDetail.quickNoteSource": "My quick notes",
    "recordDetail.secondsSuffix": "s",
    "recordDetail.timesSuffix": " times",
    "recordDetail.thoughtTitle": "Asen has thoughts",
    "recordDetail.thoughtDesc": "This note can keep expanding into actions, questions, or supporting memory.",
    "recordDetail.similarTitle": "Similar notes",
    "recordDetail.similarDemo1": "Break this idea into a next action so it is easier to follow up later.",
    "recordDetail.similarDemo2": "Add context, decisions, and open questions around the same topic.",
    "recordDetail.extendsPrefix": "",
    "recordDetail.extendsSuffix": " extensions",
    "recordDetail.noExtends": "No extensions yet. Add a comment below to continue this note.",
    "recordDetail.extendPlaceholder": "Continue with an extension...",
    "recordDetail.sendExtend": "Send",
    "recordDetail.inputMenu": "Open input menu",
    "recordDetail.noLocation": "No location info",
    "recordDetail.me": "Me",
    "recordSnapshot.title": "Memory snapshot",
    "recordSnapshot.close": "Close memory snapshot",
    "recordSnapshot.untitled": "Untitled",
    "recordSnapshot.quickNoteSource": "My quick notes",
    "recordAction.close": "Close action menu",
    "recordAction.copy": "Copy",
    "recordAction.detail": "Details",
    "recordAction.fullscreen": "Open",
    "recordAction.extend": "Extend",
    "recordAction.memorySnapshot": "Memory snapshot",
    "recordAction.moreDetail": "More details",
    "recordAction.more": "More",
    "chat.loadingMore": "Loading more...",
    "chat.loadMore": "Load more",
    "time.today": "Today",
    "time.yesterday": "Yesterday",
    "time.dayBeforeYesterday": "The day before yesterday",
    "time.justNow": "Just now",
    "time.minutesAgo": " minutes ago",
    "time.hoursAgo": " hours ago",
    "guide.avatar": "Info",
    "guide.scope": "Mobile exam rules",
    "guide.message1": "Before starting, ask Codex to read AGENTS.md and docs/candidate-rules.md, then complete the work according to those rules.",
    "guide.message2": "For each request, understand the goal and impact first, then read the related code. Keep changes focused and avoid unrelated refactors.",
    "guide.message3": "After each iteration, append the time, user input, AI final output, changed files, and verification result to your personal log under docs/codex-logs/.",
    "guide.message4": "Before submitting to GitHub, run pnpm verify:answer to ensure lint, build, iteration logs, and answer standard checks all pass.",
    "guide.message5": "The interviewer will review the final code, Git history, and Codex iteration log to understand how you used AI to iterate on the project.",
  },
  "ar-SA": {
    "tabs.records": "ملاحظات",
    "tabs.arrangements": "خطط",
    "tabs.insight": "رؤى",
    "tabs.mine": "أنا",
    "settings.title": "الإعدادات",
    "settings.appearance": "المظهر",
    "settings.language": "اللغة",
    "settings.languageDesc": "اختر لغة عرض التطبيق",
    "settings.languageSheetDesc": "اختر لغة عرض التطبيق",
    "settings.followSystem": "استخدام لغة النظام تلقائيا",
    "settings.current": "الحالي",
    "appearance.title": "المظهر",
    "appearance.theme": "نمط السمة",
    "appearance.themeSystem": "حسب النظام",
    "appearance.themeLight": "فاتح",
    "appearance.themeDark": "داكن",
    "appearance.accent": "لون التمييز",
    "appearance.icon": "أيقونة التطبيق",
    "common.back": "رجوع",
    "common.done": "تم",
    "common.selected": "محدد",
    "common.vip": "VIP",
    "composer.placeholder": "اضغط للنص، اضغط مطولا للصوت",
    "composer.recording": "جار التسجيل، اترك للإرسال",
    "composer.textPlaceholder": "سجل هذه اللحظة...",
    "composer.send": "إرسال",
  },
};

const translationAdditions: Record<string, Record<TranslationKey, string>> = {
  "zh-CN": {
    "arrangements.title": "安排",
    "arrangements.subtitle": "未来的事，轻一点放在这",
    "arrangements.searchLabel": "搜索安排",
    "arrangements.searchPlaceholder": "搜索安排、地点、相关人",
    "arrangements.searchActive": "搜索：{keyword}",
    "arrangements.clear": "清除",
    "arrangements.filter.all": "全部",
    "arrangements.filter.near": "近期",
    "arrangements.filter.later": "以后再说",
    "arrangements.filter.done": "已完成",
    "arrangements.group.all": "全部安排",
    "arrangements.group.near": "近期",
    "arrangements.group.later": "以后再说",
    "arrangements.group.done": "已完成",
    "arrangements.source.all": "全部来源",
    "arrangements.source.manual": "手动创建",
    "arrangements.source.sendToSelf": "发给自己",
    "arrangements.source.privateChat": "来自私聊",
    "arrangements.source.groupChat": "来自群聊",
    "arrangements.source.aiSuggestion": "AI 建议",
    "arrangements.sourcePrefix": "来源：{source}",
    "arrangements.today.title": "今天值得留意",
    "arrangements.today.count": "{count} 条",
    "arrangements.today.doneTitle": "今天都处理好了",
    "arrangements.today.doneDesc": "已完成的安排会留在“已完成”里，之后也可以恢复。",
    "arrangements.today.doneAction": "查看已完成",
    "arrangements.today.emptyTitle": "还没有安排",
    "arrangements.today.emptyDesc": "把接下来可能要做的事先放进来，不确定时间也没关系。",
    "arrangements.today.emptyAction": "新增安排",
    "arrangements.today.calmTitle": "今天不用急",
    "arrangements.today.futureDesc": "后面还有几条安排，可以先看看近期。",
    "arrangements.today.futureAction": "查看近期",
    "arrangements.today.noTodayDesc": "暂时没有需要今天处理的安排。",
    "arrangements.empty.noMatches": "没有匹配的安排",
    "arrangements.empty.noItems": "这里还没有安排",
    "arrangements.empty.noMatchesDesc": "换个关键词或来源试试。",
    "arrangements.empty.noItemsDesc": "把接下来可能要做的事先放进来，不确定时间也没关系。",
    "arrangements.empty.clearFilters": "清除筛选",
    "arrangements.action.create": "新增安排",
    "arrangements.action.complete": "完成",
    "arrangements.action.completeAria": "完成安排",
    "arrangements.action.restoreAria": "恢复安排",
    "arrangements.action.moveLater": "以后再说",
    "arrangements.action.restore": "重新放回安排",
    "arrangements.action.edit": "编辑",
    "arrangements.action.archive": "归档",
    "arrangements.contextCount": "关联 {count} 段上下文",
    "arrangements.candidate.title": "可能是安排",
    "arrangements.candidate.count": "{count} 条候选",
    "arrangements.candidate.aiSuggestion": "AI 建议",
    "arrangements.candidate.globalLinked": "跨聊天关联",
    "arrangements.candidate.possibleLink": "疑似关联",
    "arrangements.candidate.sourceCount": "{count} 条来源",
    "arrangements.candidate.reason": "理由：{reason}",
    "arrangements.candidate.confidence": "可信度 {percent}%",
    "arrangements.candidate.source": "来源：{excerpt}",
    "arrangements.candidate.confirm": "确认",
    "arrangements.candidate.ignore": "忽略",
    "arrangements.candidate.openSource": "查看来源",
    "arrangements.detail.title": "安排详情",
    "arrangements.detail.close": "关闭安排详情",
    "arrangements.detail.status": "状态",
    "arrangements.detail.time": "时间",
    "arrangements.detail.location": "地点",
    "arrangements.detail.people": "相关人",
    "arrangements.detail.source": "来源",
    "arrangements.detail.aiCapability": "AI 能力",
    "arrangements.detail.context": "相关上下文",
    "arrangements.detail.noLocation": "暂未设置",
    "arrangements.detail.noPeople": "暂无",
    "arrangements.editor.createTitle": "新增安排",
    "arrangements.editor.editTitle": "编辑安排",
    "arrangements.editor.confirmTitle": "确认候选安排",
    "arrangements.editor.save": "保存安排",
    "arrangements.editor.saveChanges": "保存修改",
    "arrangements.editor.saveCandidate": "保存为安排",
    "arrangements.editor.closeCreate": "关闭新增安排",
    "arrangements.editor.closeEdit": "关闭编辑安排",
    "arrangements.editor.closeConfirm": "关闭确认候选安排",
    "arrangements.editor.content": "内容",
    "arrangements.editor.contentPlaceholder": "写下接下来可能要做的事",
    "arrangements.editor.time": "时间",
    "arrangements.editor.timeHint": "不确定时间也可以先放进来。",
    "arrangements.editor.location": "地点",
    "arrangements.editor.locationPlaceholder": "医院、公司、线上...",
    "arrangements.editor.people": "相关人",
    "arrangements.editor.peoplePlaceholder": "用空格或顿号分隔",
    "arrangements.editor.note": "备注",
    "arrangements.editor.notePlaceholder": "补充背景或想法",
    "arrangements.time.none": "无时间",
    "arrangements.time.noTime": "还没有时间",
    "arrangements.time.today": "今天",
    "arrangements.time.tomorrow": "明天",
    "arrangements.time.weekday": "本周",
    "arrangements.time.date": "具体日期",
    "arrangements.time.pickDate": "选择日期",
    "arrangements.time.pickWeekday": "选择星期",
    "arrangements.time.pickPart": "选择时段",
    "arrangements.time.pickClock": "具体时间",
    "arrangements.time.clockAria": "具体几点",
    "arrangements.time.part.any": "不限时段",
    "arrangements.time.part.morning": "上午",
    "arrangements.time.part.afternoon": "下午",
    "arrangements.time.part.evening": "晚上",
    "arrangements.time.weekday.0": "周日",
    "arrangements.time.weekday.1": "周一",
    "arrangements.time.weekday.2": "周二",
    "arrangements.time.weekday.3": "周三",
    "arrangements.time.weekday.4": "周四",
    "arrangements.time.weekday.5": "周五",
    "arrangements.time.weekday.6": "周六",
    "arrangements.status.active": "进行中",
    "arrangements.status.done": "已完成",
    "arrangements.status.later": "以后再说",
    "arrangements.status.archived": "已归档",
    "arrangements.aiCapability.userOnly": "需要自己完成",
    "arrangements.aiCapability.aiAssist": "AI 可协助",
    "arrangements.aiCapability.aiExecutable": "AI 可执行",
    "aiSettings.title": "AI 接入设置",
    "aiSettings.enableTitle": "启用 AI 识别",
    "aiSettings.mode.localRules": "本地规则",
    "aiSettings.mode.enabled": "已启用",
    "aiSettings.mode.incomplete": "待补全",
    "aiSettings.enableDesc": "开启后通过同源代理转发识别；关闭时仅使用本地规则。",
    "aiSettings.baseUrl": "Base URL",
    "aiSettings.apiKey": "API Key",
    "aiSettings.model": "Model",
    "aiSettings.quickScanTitle": "快速扫描近期对话",
    "aiSettings.quickScanDesc": "扫描最近一周可能的安排；未启用或配置不完整时走本地规则。",
    "aiSettings.quickScan": "快速扫描",
    "aiSettings.scanning": "扫描中",
    "aiSettings.scan.empty": "最近一周没有可扫描的对话",
    "aiSettings.scan.scanning": "正在扫描 {count} 条近期对话",
    "aiSettings.scan.unconfigured": "AI 未启用或 API 配置不完整，快速扫描使用本地规则",
    "aiSettings.scan.summary": "AI 成功 {ai} 条，失败 {failed} 条，本地回退 {fallback} 条",
    "aiSettings.scan.success": "已整理 {count} 条可能安排（{summary}）",
    "aiSettings.scan.noResult": "最近没有发现明确安排（{summary}）",
    "aiSettings.scan.failed": "扫描失败",
    "aiSettings.localKeyTip": "API Key 仅保存在当前浏览器本地，并只发送给同源代理；代理会转发到配置的 Base URL。",
    "aiSettings.save": "保存",
    "aiSettings.reset": "重置",
    "aiSettings.saved": "AI 接入设置已保存",
    "aiSettings.resetDone": "已恢复默认设置",
    "aiSettings.switchAria": "启用 AI 识别",
    "aiSettings.diagnostics.title": "识别诊断日志",
    "aiSettings.diagnostics.desc": "记录最近的 AI 请求、错误和本地回退；不会保存完整 API Key。",
    "aiSettings.diagnostics.clear": "清空",
    "aiSettings.diagnostics.empty": "暂无日志。保存配置后点击“快速扫描”，这里会显示实际连接结果。",
    "aiSettings.diagnostics.unnamedSource": "未命名来源",
    "aiSettings.diagnostics.browser": "浏览器：{endpoint}",
    "aiSettings.diagnostics.noEndpoint": "未生成请求地址",
    "aiSettings.diagnostics.target": "代理目标：{endpoint}",
    "aiSettings.diagnostics.model": "模型：{model}",
    "aiSettings.diagnostics.key": "Key：{key}",
    "aiSettings.diagnostics.keyMissing": "未填写",
    "aiSettings.diagnostics.status": "状态：{status}",
    "aiSettings.diagnostics.duration": "耗时：{duration}ms",
    "aiSettings.diagnostics.fallbackUsed": "已回退本地规则",
    "aiSettings.diagnostics.stage.configured": "配置检查",
    "aiSettings.diagnostics.stage.request": "请求已发出",
    "aiSettings.diagnostics.stage.success": "AI 成功",
    "aiSettings.diagnostics.stage.empty": "无安排",
    "aiSettings.diagnostics.stage.httpError": "HTTP 错误",
    "aiSettings.diagnostics.stage.networkError": "网络/CORS",
    "aiSettings.diagnostics.stage.parseError": "解析失败",
    "aiSettings.diagnostics.stage.unconfigured": "未配置",
    "aiSettings.diagnostics.stage.fallback": "本地回退",
    "aiSettings.diagnostics.stage.default": "诊断",
    "recordDetail.arrangement.addCandidate": "加入安排候选",
    "recordDetail.arrangement.aiRecognize": "AI 识别安排",
    "recordDetail.arrangement.recognizing": "识别中",
    "recordDetail.arrangement.configureFirst": "先配置 AI",
    "recordDetail.arrangement.recognizeAgain": "重新识别安排",
  },
  "zh-TW": {
    "arrangements.title": "安排",
    "arrangements.subtitle": "未來的事，輕一點放在這",
    "arrangements.searchLabel": "搜尋安排",
    "arrangements.searchPlaceholder": "搜尋安排、地點、相關人",
    "arrangements.searchActive": "搜尋：{keyword}",
    "arrangements.clear": "清除",
    "arrangements.filter.all": "全部",
    "arrangements.filter.near": "近期",
    "arrangements.filter.later": "之後再說",
    "arrangements.filter.done": "已完成",
    "arrangements.group.all": "全部安排",
    "arrangements.group.near": "近期",
    "arrangements.group.later": "之後再說",
    "arrangements.group.done": "已完成",
    "arrangements.source.all": "全部來源",
    "arrangements.source.manual": "手動建立",
    "arrangements.source.sendToSelf": "發給自己",
    "arrangements.source.privateChat": "來自私聊",
    "arrangements.source.groupChat": "來自群聊",
    "arrangements.source.aiSuggestion": "AI 建議",
    "arrangements.sourcePrefix": "來源：{source}",
    "arrangements.today.title": "今天值得留意",
    "arrangements.today.count": "{count} 條",
    "arrangements.today.doneTitle": "今天都處理好了",
    "arrangements.today.doneDesc": "已完成的安排會留在「已完成」裡，之後也可以恢復。",
    "arrangements.today.doneAction": "查看已完成",
    "arrangements.today.emptyTitle": "還沒有安排",
    "arrangements.today.emptyDesc": "把接下來可能要做的事先放進來，不確定時間也沒關係。",
    "arrangements.today.emptyAction": "新增安排",
    "arrangements.today.calmTitle": "今天不用急",
    "arrangements.today.futureDesc": "後面還有幾條安排，可以先看看近期。",
    "arrangements.today.futureAction": "查看近期",
    "arrangements.today.noTodayDesc": "暫時沒有需要今天處理的安排。",
    "arrangements.empty.noMatches": "沒有符合的安排",
    "arrangements.empty.noItems": "這裡還沒有安排",
    "arrangements.empty.noMatchesDesc": "換個關鍵字或來源試試。",
    "arrangements.empty.noItemsDesc": "把接下來可能要做的事先放進來，不確定時間也沒關係。",
    "arrangements.empty.clearFilters": "清除篩選",
    "arrangements.action.create": "新增安排",
    "arrangements.action.complete": "完成",
    "arrangements.action.completeAria": "完成安排",
    "arrangements.action.restoreAria": "恢復安排",
    "arrangements.action.moveLater": "之後再說",
    "arrangements.action.restore": "重新放回安排",
    "arrangements.action.edit": "編輯",
    "arrangements.action.archive": "封存",
    "arrangements.contextCount": "關聯 {count} 段上下文",
    "arrangements.candidate.title": "可能是安排",
    "arrangements.candidate.count": "{count} 條候選",
    "arrangements.candidate.aiSuggestion": "AI 建議",
    "arrangements.candidate.globalLinked": "跨聊天關聯",
    "arrangements.candidate.possibleLink": "疑似關聯",
    "arrangements.candidate.sourceCount": "{count} 條來源",
    "arrangements.candidate.reason": "理由：{reason}",
    "arrangements.candidate.confidence": "可信度 {percent}%",
    "arrangements.candidate.source": "來源：{excerpt}",
    "arrangements.candidate.confirm": "確認",
    "arrangements.candidate.ignore": "忽略",
    "arrangements.candidate.openSource": "查看來源",
    "arrangements.detail.title": "安排詳情",
    "arrangements.detail.close": "關閉安排詳情",
    "arrangements.detail.status": "狀態",
    "arrangements.detail.time": "時間",
    "arrangements.detail.location": "地點",
    "arrangements.detail.people": "相關人",
    "arrangements.detail.source": "來源",
    "arrangements.detail.aiCapability": "AI 能力",
    "arrangements.detail.context": "相關上下文",
    "arrangements.detail.noLocation": "暫未設定",
    "arrangements.detail.noPeople": "暫無",
    "arrangements.editor.createTitle": "新增安排",
    "arrangements.editor.editTitle": "編輯安排",
    "arrangements.editor.confirmTitle": "確認候選安排",
    "arrangements.editor.save": "儲存安排",
    "arrangements.editor.saveChanges": "儲存修改",
    "arrangements.editor.saveCandidate": "儲存為安排",
    "arrangements.editor.closeCreate": "關閉新增安排",
    "arrangements.editor.closeEdit": "關閉編輯安排",
    "arrangements.editor.closeConfirm": "關閉確認候選安排",
    "arrangements.editor.content": "內容",
    "arrangements.editor.contentPlaceholder": "寫下接下來可能要做的事",
    "arrangements.editor.time": "時間",
    "arrangements.editor.timeHint": "不確定時間也可以先放進來。",
    "arrangements.editor.location": "地點",
    "arrangements.editor.locationPlaceholder": "醫院、公司、線上...",
    "arrangements.editor.people": "相關人",
    "arrangements.editor.peoplePlaceholder": "用空格或頓號分隔",
    "arrangements.editor.note": "備註",
    "arrangements.editor.notePlaceholder": "補充背景或想法",
    "arrangements.time.none": "無時間",
    "arrangements.time.noTime": "還沒有時間",
    "arrangements.time.today": "今天",
    "arrangements.time.tomorrow": "明天",
    "arrangements.time.weekday": "本週",
    "arrangements.time.date": "具體日期",
    "arrangements.time.pickDate": "選擇日期",
    "arrangements.time.pickWeekday": "選擇星期",
    "arrangements.time.pickPart": "選擇時段",
    "arrangements.time.pickClock": "具體時間",
    "arrangements.time.clockAria": "具體幾點",
    "arrangements.time.part.any": "不限時段",
    "arrangements.time.part.morning": "上午",
    "arrangements.time.part.afternoon": "下午",
    "arrangements.time.part.evening": "晚上",
    "arrangements.time.weekday.0": "週日",
    "arrangements.time.weekday.1": "週一",
    "arrangements.time.weekday.2": "週二",
    "arrangements.time.weekday.3": "週三",
    "arrangements.time.weekday.4": "週四",
    "arrangements.time.weekday.5": "週五",
    "arrangements.time.weekday.6": "週六",
    "arrangements.status.active": "進行中",
    "arrangements.status.done": "已完成",
    "arrangements.status.later": "之後再說",
    "arrangements.status.archived": "已封存",
    "arrangements.aiCapability.userOnly": "需要自己完成",
    "arrangements.aiCapability.aiAssist": "AI 可協助",
    "arrangements.aiCapability.aiExecutable": "AI 可執行",
  },
  "en-US": {
    "arrangements.title": "Plans",
    "arrangements.subtitle": "Keep future things somewhere light.",
    "arrangements.searchLabel": "Search plans",
    "arrangements.searchPlaceholder": "Search plans, places, or people",
    "arrangements.searchActive": "Search: {keyword}",
    "arrangements.clear": "Clear",
    "arrangements.filter.all": "All",
    "arrangements.filter.near": "Soon",
    "arrangements.filter.later": "Later",
    "arrangements.filter.done": "Done",
    "arrangements.group.all": "All plans",
    "arrangements.group.near": "Soon",
    "arrangements.group.later": "Later",
    "arrangements.group.done": "Done",
    "arrangements.source.all": "All sources",
    "arrangements.source.manual": "Manual",
    "arrangements.source.sendToSelf": "Send to self",
    "arrangements.source.privateChat": "Private chat",
    "arrangements.source.groupChat": "Group chat",
    "arrangements.source.aiSuggestion": "AI suggestion",
    "arrangements.sourcePrefix": "Source: {source}",
    "arrangements.today.title": "Worth noting today",
    "arrangements.today.count": "{count} items",
    "arrangements.today.doneTitle": "All set for today",
    "arrangements.today.doneDesc": "Completed plans stay under Done and can be restored later.",
    "arrangements.today.doneAction": "View done",
    "arrangements.today.emptyTitle": "No plans yet",
    "arrangements.today.emptyDesc": "Save what may need doing next. An exact time is optional.",
    "arrangements.today.emptyAction": "Add plan",
    "arrangements.today.calmTitle": "No rush today",
    "arrangements.today.futureDesc": "There are a few plans later. You can check what is coming soon.",
    "arrangements.today.futureAction": "View soon",
    "arrangements.today.noTodayDesc": "Nothing needs attention today.",
    "arrangements.empty.noMatches": "No matching plans",
    "arrangements.empty.noItems": "No plans here yet",
    "arrangements.empty.noMatchesDesc": "Try another keyword or source.",
    "arrangements.empty.noItemsDesc": "Save what may need doing next. An exact time is optional.",
    "arrangements.empty.clearFilters": "Clear filters",
    "arrangements.action.create": "Add plan",
    "arrangements.action.complete": "Done",
    "arrangements.action.completeAria": "Complete plan",
    "arrangements.action.restoreAria": "Restore plan",
    "arrangements.action.moveLater": "Later",
    "arrangements.action.restore": "Restore",
    "arrangements.action.edit": "Edit",
    "arrangements.action.archive": "Archive",
    "arrangements.contextCount": "{count} context items",
    "arrangements.candidate.title": "Maybe a plan",
    "arrangements.candidate.count": "{count} candidates",
    "arrangements.candidate.aiSuggestion": "AI suggestion",
    "arrangements.candidate.globalLinked": "Cross-chat linked",
    "arrangements.candidate.possibleLink": "Possible link",
    "arrangements.candidate.sourceCount": "{count} sources",
    "arrangements.candidate.reason": "Reason: {reason}",
    "arrangements.candidate.confidence": "Confidence {percent}%",
    "arrangements.candidate.source": "Source: {excerpt}",
    "arrangements.candidate.confirm": "Confirm",
    "arrangements.candidate.ignore": "Ignore",
    "arrangements.candidate.openSource": "View source",
    "arrangements.detail.title": "Plan details",
    "arrangements.detail.close": "Close plan details",
    "arrangements.detail.status": "Status",
    "arrangements.detail.time": "Time",
    "arrangements.detail.location": "Place",
    "arrangements.detail.people": "People",
    "arrangements.detail.source": "Source",
    "arrangements.detail.aiCapability": "AI capability",
    "arrangements.detail.context": "Related context",
    "arrangements.detail.noLocation": "Not set",
    "arrangements.detail.noPeople": "None",
    "arrangements.editor.createTitle": "Add plan",
    "arrangements.editor.editTitle": "Edit plan",
    "arrangements.editor.confirmTitle": "Confirm candidate",
    "arrangements.editor.save": "Save plan",
    "arrangements.editor.saveChanges": "Save changes",
    "arrangements.editor.saveCandidate": "Save as plan",
    "arrangements.editor.closeCreate": "Close add plan",
    "arrangements.editor.closeEdit": "Close edit plan",
    "arrangements.editor.closeConfirm": "Close confirm candidate",
    "arrangements.editor.content": "Content",
    "arrangements.editor.contentPlaceholder": "Write what may need doing next",
    "arrangements.editor.time": "Time",
    "arrangements.editor.timeHint": "You can save it even without an exact time.",
    "arrangements.editor.location": "Place",
    "arrangements.editor.locationPlaceholder": "Hospital, office, online...",
    "arrangements.editor.people": "People",
    "arrangements.editor.peoplePlaceholder": "Separate with spaces or commas",
    "arrangements.editor.note": "Note",
    "arrangements.editor.notePlaceholder": "Add context or thoughts",
    "arrangements.time.none": "No time",
    "arrangements.time.noTime": "No time yet",
    "arrangements.time.today": "Today",
    "arrangements.time.tomorrow": "Tomorrow",
    "arrangements.time.weekday": "This week",
    "arrangements.time.date": "Date",
    "arrangements.time.pickDate": "Pick date",
    "arrangements.time.pickWeekday": "Pick weekday",
    "arrangements.time.pickPart": "Pick time of day",
    "arrangements.time.pickClock": "Exact time",
    "arrangements.time.clockAria": "Exact time",
    "arrangements.time.part.any": "Any time",
    "arrangements.time.part.morning": "Morning",
    "arrangements.time.part.afternoon": "Afternoon",
    "arrangements.time.part.evening": "Evening",
    "arrangements.time.weekday.0": "Sun",
    "arrangements.time.weekday.1": "Mon",
    "arrangements.time.weekday.2": "Tue",
    "arrangements.time.weekday.3": "Wed",
    "arrangements.time.weekday.4": "Thu",
    "arrangements.time.weekday.5": "Fri",
    "arrangements.time.weekday.6": "Sat",
    "arrangements.status.active": "Active",
    "arrangements.status.done": "Done",
    "arrangements.status.later": "Later",
    "arrangements.status.archived": "Archived",
    "arrangements.aiCapability.userOnly": "Manual",
    "arrangements.aiCapability.aiAssist": "AI assist",
    "arrangements.aiCapability.aiExecutable": "AI executable",
    "aiSettings.title": "AI settings",
    "aiSettings.enableTitle": "Enable AI recognition",
    "aiSettings.mode.localRules": "Local rules",
    "aiSettings.mode.enabled": "Enabled",
    "aiSettings.mode.incomplete": "Incomplete",
    "aiSettings.enableDesc": "When enabled, recognition is forwarded through the same-origin proxy. When disabled, only local rules are used.",
    "aiSettings.baseUrl": "Base URL",
    "aiSettings.apiKey": "API Key",
    "aiSettings.model": "Model",
    "aiSettings.quickScanTitle": "Quick scan recent chats",
    "aiSettings.quickScanDesc": "Scan likely plans from the last week. If AI is off or incomplete, local rules are used.",
    "aiSettings.quickScan": "Quick scan",
    "aiSettings.scanning": "Scanning",
    "aiSettings.scan.empty": "No conversations from the last week to scan.",
    "aiSettings.scan.scanning": "Scanning {count} recent conversations",
    "aiSettings.scan.unconfigured": "AI is off or incomplete, so quick scan is using local rules.",
    "aiSettings.scan.summary": "AI succeeded {ai}, failed {failed}, local fallback {fallback}",
    "aiSettings.scan.success": "Saved {count} possible plans ({summary})",
    "aiSettings.scan.noResult": "No clear plans found ({summary})",
    "aiSettings.scan.failed": "Scan failed",
    "aiSettings.localKeyTip": "The API Key is stored only in this browser and sent only to the same-origin proxy, which forwards to your Base URL.",
    "aiSettings.save": "Save",
    "aiSettings.reset": "Reset",
    "aiSettings.saved": "AI settings saved",
    "aiSettings.resetDone": "Default settings restored",
    "aiSettings.switchAria": "Enable AI recognition",
    "aiSettings.diagnostics.title": "Recognition diagnostics",
    "aiSettings.diagnostics.desc": "Shows recent AI requests, errors, and local fallback. The full API Key is never stored.",
    "aiSettings.diagnostics.clear": "Clear",
    "aiSettings.diagnostics.empty": "No logs yet. Save settings and tap Quick scan to see connection results.",
    "aiSettings.diagnostics.unnamedSource": "Unnamed source",
    "aiSettings.diagnostics.browser": "Browser: {endpoint}",
    "aiSettings.diagnostics.noEndpoint": "No request URL",
    "aiSettings.diagnostics.target": "Proxy target: {endpoint}",
    "aiSettings.diagnostics.model": "Model: {model}",
    "aiSettings.diagnostics.key": "Key: {key}",
    "aiSettings.diagnostics.keyMissing": "Missing",
    "aiSettings.diagnostics.status": "Status: {status}",
    "aiSettings.diagnostics.duration": "Duration: {duration}ms",
    "aiSettings.diagnostics.fallbackUsed": "Used local fallback",
    "aiSettings.diagnostics.stage.configured": "Config check",
    "aiSettings.diagnostics.stage.request": "Requested",
    "aiSettings.diagnostics.stage.success": "AI success",
    "aiSettings.diagnostics.stage.empty": "No plan",
    "aiSettings.diagnostics.stage.httpError": "HTTP error",
    "aiSettings.diagnostics.stage.networkError": "Network/CORS",
    "aiSettings.diagnostics.stage.parseError": "Parse failed",
    "aiSettings.diagnostics.stage.unconfigured": "Unconfigured",
    "aiSettings.diagnostics.stage.fallback": "Local fallback",
    "aiSettings.diagnostics.stage.default": "Diagnostic",
    "recordDetail.arrangement.addCandidate": "Add as plan candidate",
    "recordDetail.arrangement.aiRecognize": "Recognize plan with AI",
    "recordDetail.arrangement.recognizing": "Recognizing",
    "recordDetail.arrangement.configureFirst": "Configure AI first",
    "recordDetail.arrangement.recognizeAgain": "Recognize again",
  },
};

Object.entries(translationAdditions).forEach(([locale, additions]) => {
  translations[locale] = {
    ...(translations[locale] ?? {}),
    ...additions,
  };
});

const localeAliases: Record<string, string> = {
  zh: "zh-CN",
  en: "en-US",
  ar: "ar-SA",
  de: "de-DE",
  es: "es-ES",
  fr: "fr-FR",
  id: "id-ID",
  it: "it-IT",
  ja: "ja-JP",
  ko: "ko-KR",
  pt: "pt-BR",
  ru: "ru-RU",
  th: "th-TH",
  tr: "tr-TR",
  vi: "vi-VN",
};

function readStoredPreferences(): PreferencesState {
  if (typeof window === "undefined") return defaultPreferences;

  try {
    const rawValue = window.localStorage.getItem(storageKey);
    if (!rawValue) return defaultPreferences;
    const parsed = JSON.parse(rawValue) as Partial<PreferencesState>;
    return {
      themeMode: isThemeMode(parsed.themeMode) ? parsed.themeMode : defaultPreferences.themeMode,
      accentColor: isAccentColor(parsed.accentColor)
        ? parsed.accentColor
        : defaultPreferences.accentColor,
      appIcon: parsed.appIcon === "bright" ? "bright" : defaultPreferences.appIcon,
      localeCode: isLocaleCode(parsed.localeCode) ? parsed.localeCode : defaultPreferences.localeCode,
    };
  } catch {
    return defaultPreferences;
  }
}

function isThemeMode(value: unknown): value is ThemeMode {
  return value === "system" || value === "light" || value === "dark";
}

function isAccentColor(value: unknown): value is AccentColor {
  return value === "green" || value === "purple" || value === "blue" || value === "pink";
}

function isLocaleCode(value: unknown): value is LocaleCode {
  return supportedLocales.some((option) => option.code === value);
}

function getSystemTheme(): ResolvedTheme {
  if (typeof window === "undefined") return "light";
  return window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light";
}

function resolveLocale(localeCode: LocaleCode): string {
  if (localeCode) {
    return supportedLocales.find((option) => option.code === localeCode)?.locale ?? "zh-CN";
  }

  if (typeof navigator === "undefined") return "zh-CN";
  const browserLocale = navigator.language || "zh-CN";
  const exactMatch = supportedLocales.find((option) => option.locale === browserLocale);
  if (exactMatch?.locale) return exactMatch.locale;
  return localeAliases[browserLocale.split("-")[0]] ?? "en-US";
}

function getLanguageDirection(locale: string): "ltr" | "rtl" {
  return locale.startsWith("ar") ? "rtl" : "ltr";
}

function getTranslation(locale: string, key: TranslationKey) {
  return (
    translationAdditions[locale]?.[key] ??
    translationAdditions[locale.split("-")[0]]?.[key] ??
    translations[locale]?.[key] ??
    translations[locale.split("-")[0]]?.[key] ??
    translationAdditions["en-US"]?.[key] ??
    translations["en-US"]?.[key] ??
    translationAdditions["zh-CN"]?.[key] ??
    translations["zh-CN"][key] ??
    key
  );
}

function formatTranslation(template: string, values?: TranslationValues) {
  if (!values) return template;
  return template.replace(/\{(\w+)\}/g, (match, valueKey) => {
    const value = values[valueKey];
    return value === undefined ? match : String(value);
  });
}

type PreferencesContextValue = PreferencesState & {
  resolvedTheme: ResolvedTheme;
  resolvedLocale: string;
  direction: "ltr" | "rtl";
  isVip: boolean;
  setThemeMode: (value: ThemeMode) => void;
  setAccentColor: (value: AccentColor) => void;
  setAppIcon: (value: AppIcon) => void;
  setLocaleCode: (value: LocaleCode) => void;
  t: (key: TranslationKey, values?: TranslationValues) => string;
};

const PreferencesContext = React.createContext<PreferencesContextValue | null>(null);

export function PreferencesProvider({ children }: { children: React.ReactNode }) {
  const [preferences, setPreferences] = React.useState(readStoredPreferences);
  const [systemTheme, setSystemTheme] = React.useState<ResolvedTheme>(getSystemTheme);
  const [systemLocaleTick, setSystemLocaleTick] = React.useState(0);

  React.useEffect(() => {
    window.localStorage.setItem(storageKey, JSON.stringify(preferences));
  }, [preferences]);

  React.useEffect(() => {
    const media = window.matchMedia("(prefers-color-scheme: dark)");
    const handleChange = () => setSystemTheme(media.matches ? "dark" : "light");
    media.addEventListener("change", handleChange);
    return () => media.removeEventListener("change", handleChange);
  }, []);

  React.useEffect(() => {
    const handleLanguageChange = () => setSystemLocaleTick((value) => value + 1);
    window.addEventListener("languagechange", handleLanguageChange);
    return () => window.removeEventListener("languagechange", handleLanguageChange);
  }, []);

  const resolvedTheme =
    preferences.themeMode === "system" ? systemTheme : preferences.themeMode;
  const resolvedLocale = React.useMemo(
    () => {
      void systemLocaleTick;
      return resolveLocale(preferences.localeCode);
    },
    [preferences.localeCode, systemLocaleTick]
  );
  const direction = getLanguageDirection(resolvedLocale);

  React.useEffect(() => {
    document.documentElement.dataset.theme = resolvedTheme;
    document.documentElement.dataset.accent = preferences.accentColor;
    document.documentElement.lang = resolvedLocale;
    document.documentElement.dir = direction;
  }, [direction, preferences.accentColor, resolvedLocale, resolvedTheme]);

  const t = React.useCallback(
    (key: TranslationKey, values?: TranslationValues) =>
      formatTranslation(getTranslation(resolvedLocale, key), values),
    [resolvedLocale]
  );

  const updatePreference = React.useCallback(
    <Key extends keyof PreferencesState>(key: Key, value: PreferencesState[Key]) => {
      setPreferences((current) => ({ ...current, [key]: value }));
    },
    []
  );

  const value = React.useMemo<PreferencesContextValue>(
    () => ({
      ...preferences,
      resolvedTheme,
      resolvedLocale,
      direction,
      isVip: false,
      setThemeMode: (themeMode) => updatePreference("themeMode", themeMode),
      setAccentColor: (accentColor) => updatePreference("accentColor", accentColor),
      setAppIcon: (appIcon) => updatePreference("appIcon", appIcon),
      setLocaleCode: (localeCode) => updatePreference("localeCode", localeCode),
      t,
    }),
    [direction, preferences, resolvedLocale, resolvedTheme, t, updatePreference]
  );

  return React.createElement(
    PreferencesContext.Provider,
    { value },
    children
  );
}

export function usePreferences() {
  const value = React.useContext(PreferencesContext);
  if (!value) {
    throw new Error("usePreferences must be used within PreferencesProvider");
  }
  return value;
}

export function getLocaleDisplayName(localeCode: LocaleCode, resolvedLocale: string) {
  if (localeCode === "") return supportedLocales[0].displayName;
  return (
    supportedLocales.find((option) => option.code === localeCode)?.displayName ??
    resolvedLocale
  );
}
